# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ola Zytek"
description: Connecting humans and AI.

email: alexandra.zytek@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cover4.jpg"

name: 'Alexandra Zytek'
author: 'Alexandra Zytek'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: 

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: github
    url: https://github.com/zyteka
    desc: Follow me on GitHub
    share_url:
    share_title:
    share_link:

  - icon: linkedin-square
    url: https://www.linkedin.com/in/alexandra-ola-zytek/
    desc: Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon: graduation-cap
    url: https://scholar.google.com/citations?user=b4_8J8AAAAAJ&hl=en
    desc: View my Google Scholar profile
    share_url:
    share_title:
    share_link:

  - icon: file-text
    url: https://drive.google.com/file/d/1PfZQeytJC_u9T4lqYUDCc1rTuzUSUVRp/view?usp=sharing
    desc: CV
    share_url:
    share_title:
    share_link:

